# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63b91a684a4e51d34de1cbf9531d11103731c30c5e4b79e22d57b9be12ca60e50e6ee3594198a9ce4e68e4720e1d8d2289c99c229b4e49b8e56d68f68cb1d776

test:
  secret_key_base: 2eea77eecb0cbcb9062c072b00c38979f5fe708bb32b783769b832fad226c4272bd1ee49e16b9dc4beef6d653c38dd1cfcea3e5c027fe4d9f984025b9c827c27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
